<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="mamta-Latitude-3400" failures="11" tests="19" name="Test" time="419.681" errors="0" timestamp="2021-01-25T15:21:03 EST">
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.861">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="10.679"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.385"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.254"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.999"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.285"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.19"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.748">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="8.276"/>
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="10.094">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.814">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="14.511">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.114">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="10.009">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.725">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="10.148">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="10.242">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_test" name="contact_Test" time="9.451">
    <failure type="java.lang.AssertionError" message="expected [Contact Us - Algoworks] but found [Thank You - Algoworks]">
      <![CDATA[java.lang.AssertionError: expected [Contact Us - Algoworks] but found [Thank You - Algoworks]
at com.algoworks.contactUs.TestClass.contact_test.contact_Test(contact_test.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- contact_Test -->
  <testcase classname="com.algoworks.contactUs.TestClass.contact_btn_test" name="contact_Button_Click" time="5.302"/>
  <testcase classname="com.algoworks.contactUs.PageObjects.BaseClass" name="@BeforeSuite setUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase classname="com.algoworks.contactUs.PageObjects.BaseClass" name="@AfterSuite TearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite TearDown -->
</testsuite> <!-- Test -->
